advice_lancing/urls.py
from django.contrib import admin
from django.urls import path, include
from markdownx import urls as markdownx
from django.conf.urls import url
from blog import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('special/', views.special, name = 'special'),
    path('logout/', views.user_logout, name = 'logout'),
    url(r'^questions/', include('questions.urls', namespace='questions')),

]

urlpatterns += [
    url(r'^markdownx/', include(markdownx))
]

blog/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'blog'


urlpatterns = [
    path('', views.allblogs , name='allblogs'),
    path('<int:blog_id>/', views.detail, name="detail"),
    path('about/', views.about, name ="about"),
    path('dark/', views.dark, name ="dark"),
    path('contact/', views.contact, name="contact"),
    path('register/', views.register, name ='register'),
    path('user_login', views.user_login, name ='user_login'),
]

#if not settings.DEBUG: urlpatterns += [ url(r'^uploads/(?P<path>.)$', serve,{'document_root': settings.MEDIA_ROOT})]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

questions/urls.py
from django.conf.urls import url
from .views import (question_list, 
                    question_detail, 
                    question_ask, 
                    question_update, 
                    category_list, 
                    category,
                    answer_update,
                    question_delete,
                    answer_delete,
                    notification)


app_name ='question'


urlpatterns = [
    url(r'^list/$', question_list, name='question_list'),
    url(r'^ask/$', question_ask, name='question_ask'),
    url(r'^notifications/$', notification, name='notification'),
    url(r'^categories/$', category_list, name='category_list'),
    url(r'^categories/(?P<slug>[\w-]+)/$', category, name='category'),
    url(r'^(?P<slug>[\w-]+)/delete/$', question_delete, name='question_delete'),
    url(r'^(?P<slug>[\w-]+)/edit/$', question_update, name='question_update'),
    url(r'^(?P<slug>[\w-]+)/answer/(?P<pk>\d+)/edit/$', answer_update, name='answer_update'),
    url(r'^(?P<slug>[\w-]+)/answer/(?P<pk>\d+)/delete/$', answer_delete, name='answer_delete'),
    url(r'^(?P<slug>[\w-]+)/$', question_detail, name='question_detail'),
]

questions/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.
User = settings.AUTH_USER_MODEL


class Category(models.Model):
    name = models.CharField(max_length=128, unique=True, verbose_name="category")
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("questions:category", kwargs={"slug": self.slug})

    class Meta:
        ordering = ['-id']


class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    qus = models.CharField(max_length=256, verbose_name="question")
    details = models.TextField(blank=True)
    slug = models.SlugField(unique=True, max_length=256)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.qus

    def get_absolute_url(self):
        return reverse("questions:question_detail", kwargs={"slug": self.slug})

    class Meta:
        ordering = ['-updated', '-created']

    def _get_unique_slug(self):
        slug = slugify(self.qus)
        unique_slug = slug
        num = 1
        while Question.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug
 
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super(Question, self).save()


class Answer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    ans = models.TextField(verbose_name="answer")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question.qus

    class Meta:
        ordering = ['-updated', '-created']


class SendNotification(models.Model):
    user = models.ForeignKey(User, related_name='user',on_delete=models.CASCADE)
    from_user = models.ForeignKey(User, related_name='from_user',on_delete=models.CASCADE)
    question = models.ForeignKey(Question,on_delete=models.CASCADE)
    message = models.CharField(max_length=256)
    sent = models.DateTimeField(auto_now_add=True)
    viewed = models.BooleanField(default=False)

    def __str__(self):
        return self.question.qus

    class Meta:
        ordering = ['-sent']

questions/forms.py
from django import forms
from .models import Question, Answer



class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ["qus", "details", "category"]


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ["ans"]

questions/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from .forms import QuestionForm, AnswerForm
from .models import Category, Question, Answer, SendNotification
# Create your views here.


def question_list(request):
    queryset = Question.objects.all()

    query = request.GET.get("q")   
    if query:
        queryset = queryset.filter(
            Q(qus__icontains=query)|
            Q(category__name__icontains=query)
            ).distinct()

    paginator = Paginator(queryset, 12)
    page = request.GET.get("page")
    try:
        query_list = paginator.page(page)
    except PageNotAnInteger:
        query_list = paginator.page(1)
    except EmptyPage:
        query_list = paginator.page(paginator.num_pages)

    context = { "query_list": query_list }
    return render(request, "questions/question_list.html", context)


def question_detail(request, slug=None):
    question = get_object_or_404(Question, slug=slug)
    answers_list = Answer.objects.filter(question=question)
    context = { "question": question,
                "answers_list": answers_list,
                 }
    if request.user.is_authenticated:
        form = AnswerForm(request.POST or None)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.user = request.user
            answer.question = question
            answer.save()
            messages.success(request, 'Answer was Posted.')
            form = AnswerForm()    
        context = { "question": question,
                    "form": form,
                    "answers_list": answers_list,
                  }
    return render(request, "questions/question_detail.html", context)



def question_ask(request):
    form = QuestionForm(request.POST or None)
    if form.is_valid():
        question = form.save(commit=False)
        question.user = request.user
        question.save()
        messages.success(request, 'Question was Posted.')
        return redirect(question.get_absolute_url())
    context = { "form": form,
                "title": "Ask Question"
              }
    return render(request, "questions/ask.html", context)



def question_update(request, slug=None):
    instance = get_object_or_404(Question, slug=slug)
    if instance.user != request.user:
        raise Http404
    else:
        form = QuestionForm(request.POST or None, instance=instance)
        if form.is_valid():
            question = form.save(commit=False)
            question.user = request.user
            question.save()
            messages.success(request, 'Question was Updated.')
            return redirect(question.get_absolute_url())
        context = { "form": form,
                    "title": "Edit Question"
                    }
    return render(request, "questions/ask.html", context)



def question_delete(request, slug=None):
    question = get_object_or_404(Question, slug=slug)
    if not request.user.is_authenticated:
        raise Http404 
    else:
        if question.user != request.user:
            raise Http404
        else:
            question.delete() 
            messages.error(request, 'Question was Deleted.')
            return redirect(request.user.get_absolute_url()) 



def answer_update(request, slug=None, pk=None):
    question = get_object_or_404(Question, slug=slug)
    instance = get_object_or_404(Answer, pk=pk)
    if instance.user != request.user:
        raise Http404
    else:
        form = AnswerForm(request.POST or None, instance=instance)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.user = request.user
            answer.question = question
            answer.save()
            messages.success(request, 'Answer was Updated.')
            return redirect(question.get_absolute_url())
        context = { "form": form,
                    "title": "Update Answer"
                    }
    return render(request, "questions/answer.html", context)



def answer_delete(request, slug=None, pk=None):
    question = get_object_or_404(Question, slug=slug)
    answer = get_object_or_404(Answer, pk=pk)
    if not request.user.is_authenticated:
        raise Http404 
    else:
        if answer.user != request.user:
            raise Http404
        else:
            answer.delete() 
            messages.error(request, 'Answer was Deleted.')
            return redirect(question.get_absolute_url())


def category_list(request):
    categories = Category.objects.all()
    context = { "categories": categories }
    return render(request, "questions/category_list.html", context)


def category(request, slug=None):
    category = get_object_or_404(Category, slug=slug)   
    queryset = category.question_set.all()

    query = request.GET.get("q")   
    if query:
        queryset = queryset.filter(
            Q(qus__icontains=query)
            ).distinct()

    paginator = Paginator(queryset, 12)
    page = request.GET.get("page")
    try:
        query_list = paginator.page(page)
    except PageNotAnInteger:
        query_list = paginator.page(1)
    except EmptyPage:
        query_list = paginator.page(paginator.num_pages)
        
    context = { "query_list": query_list,
                "category": category
              }
    return render(request, "questions/category.html", context)



def notification(request):
    user = request.user
    notification = SendNotification.objects.filter(user=user)
    notification.update(viewed=True)

    paginator = Paginator(notification, 12)
    page = request.GET.get("page")
    try:
        query_list = paginator.page(page)
    except PageNotAnInteger:
        query_list = paginator.page(1)
    except EmptyPage:
        query_list = paginator.page(paginator.num_pages)

    context = { "query_list": query_list }
    return render(request, "questions/notification.html", context)

templates/questions/answer.html
{% extends "questions/base.html" %}
{% load crispy_forms_tags %}
{% block title %} {{ title }} | {{ block.super }}{% endblock title %}

{% block tinymce %} 
    {{ form.media }}
{% endblock tinymce %}

{% block content %}
<h2>{{ title }}</h2><hr>
<form method="POST" action="" >
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <input class="btn btn-success" type="submit" value='Submit'>
</form>
{% endblock content %}

templates/questions/ask.html
{% extends "questions/base.html" %}
{% load crispy_forms_tags %}
{% block title %} {{ title }} | {{ block.super }}{% endblock title %}

{% block content %}
<h2>{{ title }}</h2><hr>
<form method="POST" action="" >
    {% csrf_token %}
    {{ form|crispy }}
    <br>
    <input class="btn btn-success" type="submit" value='Submit'>
</form>
{% endblock content %}

templates/questions/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>{% block title %} Your-Query {% endblock title %}</title>
    <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href='{% static "css/base.css" %}'>
        <link rel="stylesheet" href='{% static "css/bootstrap.min.css" %}'>
        <link rel="stylesheet" href='{% static "css/bootstrap-theme.min.css" %}'>
<!--         <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"> -->
    </head>
    <body>
        {% include "questions/navbar.html" %}
            <div class="container" style="padding-top: 80px;" >
                {% block content %}

                {% endblock content %}
            </div>
        {% include "questions/footer.html" %}

<!-- Latest compiled and minified JavaScript -->
        <script type="text/javascript" src="{% static 'js/jquery.min.js' %}" ></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}" ></script>

<!--         <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> -->
    </body>
</html>

templates/questions/category.html
{% extends "questions/base.html" %}

{% block title %} {{ category }} Questions | {{ block.super }}{% endblock title %}

{% block content %}

{% include "questions/search.html" %}

<a class="btn btn-success" href="{% url 'questions:question_ask' %}">Ask your Questions</a>
<hr>

<h1>{{ category }} Questions</h1>
<hr>

{% for question in query_list %}
<div class="list-group">
  <div class="list-group-item list-group-item-action flex-column align-items-start">
    <div class="d-flex w-100 justify-content-between">
      <h4 class="mb-1"><b><a href="{{question.get_absolute_url}}" >{{ question.qus }}</a></b>
      <small>Asked {{ question.updated|timesince }} ago By <b>
      <a href="{{question.user.get_absolute_url}}" >{{ question.user.username }}</a>
      </b></small></h4>
      <small><b>Category:</b> <a href="{{question.category.get_absolute_url}}" >{{ question.category }}</a></small>
    </div>
    <p class="mb-1">{{ question.details|linebreaks|truncatechars:120 }}</p>

  </div>
</div>
{% endfor %}

{% include "questions/paginator.html" %}

{% endblock content %}

templates/questions/category_list.html
{% extends "questions/base.html" %}

{% block title %} Categories | {{ block.super }}{% endblock title %}

{% block content %}
<div class="container">
    <h2>Categories</h2>
    <hr>
<div>
<div class="list-group">
{% for obj in categories %}
  <a href="{{ obj.get_absolute_url }}" class="list-group-item">{{obj.name}}</a>
{% endfor %}
</div>
{% endblock content %}

templates/questions/footer.html
<hr>
<footer class="footer navbar-fixed">
    <!--Footer Links-->
    <div class="container-fluid">
        <div class="row">
            <!--First column-->
            <div class="col-md-6">
                <h4 class="title"><b>Footer Content</b></h4>
                <p>Here you can use rows and columns here to organize your footer content.</p>
            </div>
            <!--/.First column-->
            <!--Second column-->
            <div class="col-md-6">
                <h5 class="title"><b>Links</b></h5>
                <a href="{% url 'questions:question_list' %}">Questions</a> |&nbsp;
                <a href="{% url 'questions:category_list' %}">Categories</a> |&nbsp;
               
                <a href="{% url 'blog:contact' %}">Contact Us</a>

            </div>
            <!--/.Second column-->
        </div>
    </div>
    <!--/.Footer Links-->
    <!--Copyright-->
    <div class="footer-copyright">
        <div class="container-fluid">
            © 2020 Copyright: <a href="http://127.0.0.1:8000/"> Advise lance query</a>
        </div>
    </div>
    <!--/.Copyright-->
</footer>
<br>

templates/questions/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

templates/questions/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'blog:allblogs' %}" style="padding-left: 30px;">Advice Lance Query</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'questions:question_list' %}">Questions</a></li>
        <li><a href="{% url 'questions:category_list' %}">Categories</a></li>
        <li><a href="{% url 'questions:question_ask' %}">Ask</a></li>
        <a class="navbar-brand" href="{% url 'blog:allblogs' %}" style="padding-left: 30px;">Blogs</a>
      </ul>
      
      <ul class="nav navbar-nav navbar-right" style="padding-right: 30px;">
        {% if request.user.is_authenticated %}
          {% if request.user.picture %}
            <li style="padding-top: 7px;"><img title="profile image" class="img-circle" src="{{ request.user.picture.url }}" id="nav-img"></li>
          {% endif %}
        <li class="dropdown">
          <a href="{{request.user.get_absolute_url}}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          {{ request.user.username }} 
          {% if not_viewed %}
          &nbsp;<span class="badge">{{ not_viewed }}</span>
          {% endif %}
          <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
              <!-- <li><a href="{{request.user.get_absolute_url}}">Profile</a></li> -->
              <li role="separator" class="divider"></li>
              <li><a href="{% url 'questions:notification' %}">Notifications &nbsp; &nbsp;<span class="badge">{{ not_viewed }}</span></a></li>
              <li role="separator" class="divider"></li>
              <li><a href="{% url 'logout' %}">Logout</a></li>
          </ul>
        </li>
        {% else %}
        <li><a href="{% url 'blog:user_login' %}">Login</a></li>
        <li><a href="{% url 'blog:register' %}">Register</a></li>
        {% endif %}
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

templates/questions/notification.html
{% extends "questions/base.html" %}

{% block title %} Notifications | {{ block.super }}{% endblock title %}

{% block content %}

<h1>Notifications</h1>
<hr>
{% if query_list %}

{% for obj in query_list %}
    <div class="list-group">
    <a href="{{ obj.question.get_absolute_url }}" class="list-group-item list-group-item-action flex-column align-items-start">
    <div class="d-flex w-100 justify-content-between">
      <h4 class="mb-1"><b>{{ obj.message }} for "{{ obj.question }}"</b></h4>
        {{ obj.sent|timesince }} ago from <b>{{ obj.from_user }}</b>
    </div>
    <p class="mb-1">{{ question.details|linebreaks|truncatechars:120 }}</p>

  </a>
</div>

{% endfor %}

{% else %}

No Notifications Found.

{% endif %}

{% include "questions/paginator.html" %}

{% endblock content %}

templates/questions/paginator.html
<div style="float: right;">
<div class="pagination">
    <em class="step-links">
        {% if query_list.has_previous %}
            <a href="?page={{ query_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        &nbsp;<em class="current">
            Page {{ query_list.number }} of {{ query_list.paginator.num_pages }}.
        </em>&nbsp;

        {% if query_list.has_next %}
            <a href="?page={{ query_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </em>
</div>
</div>

templates/questions/question_detail.html
{% extends "questions/base.html" %}
{% load crispy_forms_tags %}
{% block title %} Question Details | {{ block.super }}{% endblock title %}

{% block content %}
{% include "questions/messages.html" %}
<h2>{{ question.qus }}
<small>Asked by <a href="{{question.user.get_absolute_url}}">{{ question.user.username }}</a></small>
{% if request.user == question.user %}
<span style="float: right;">
<a class="btn btn-success btn-sm" href="{{question.get_absolute_url}}edit/" role="button">Edit</a>
<a class="btn btn-danger btn-sm" href="{{question.get_absolute_url}}delete/" role="button">Delete</a>
</span>
{% endif %}
</h2> 
<hr>
<b>Created: </b>{{ question.created }}<br>
<b>Updated: </b>{{ question.updated }}<br>
<b>Category: </b><a href="{{question.category.get_absolute_url}}">{{ question.category }}</a>
<hr>
<strong>Details</strong>
<hr>
<p>{{ question.details }}</p>
<hr>

{% if request.user.is_authenticated %}
<form method="POST" action="" >
    {% csrf_token %}
    {{ form|crispy }}

    <input class="btn btn-success" type="submit" value='Submit'>
</form>
<hr>
{% endif %}

<div class="container">

    <div class="row">

        <div class="col-sm-12">

            <h2>Answers:</h2>

        </div><!-- /col-sm-12 -->

    </div><!-- /row -->

    <hr>

    {% for answer in answers_list %}

        <!-- {% if answer.user.picture %}
        <div class="col-sm-1">

            <div class="thumbnail">

                <img class="img-responsive user-photo" src="{{ answer.user.picture.url }}">

            </div>/thumbnail

        </div>
        {% else %}
                <div class="col-sm-1">
                <h4 align="center"><small>No <br>Image</small></h4>
        </div>
        {% endif %} -->

        <div class="col-sm-11">

            <div class="panel panel-default">

                <div class="panel-heading">
                    <strong>
                    <a href="{{answer.user.get_absolute_url}}">{{ answer.user.username }}</a>
                    </strong>
                    <span style="padding-left: 5px;" >
                    {% if request.user == answer.user %}
                        (<a href="{% url 'questions:answer_update' slug=answer.question.slug pk=answer.pk %}">Edit</a>&nbsp;/
                        <a href="{% url 'questions:answer_delete' slug=answer.question.slug pk=answer.pk %}">Delete</a>)
                    {% endif %}
                    </span> 
                    <span style="float: right;" class="text-muted">
                    {{ answer.updated|timesince }} ago
                    </span>

                </div>

                <div class="panel-body">
                    {{ answer.ans }}
                </div><!-- /panel-body -->

            </div><!-- /panel panel-default -->

            <hr>

        </div><!-- /col-sm-5 -->
  {% endfor %}
</div><!-- /container -->

{% endblock content %}

templates/questions/question_list.html
{% extends "questions/base.html" %}

{% block title %} Questions | {{ block.super }}{% endblock title %}

{% block content %}


{% include "questions/search.html" %}

<a class="btn btn-success" href="{% url 'questions:question_ask' %}">Ask your Questions</a>
<hr>

<h1>All Questions</h1>
<hr>
{% for question in query_list %}
<div class="list-group">
  <div class="list-group-item list-group-item-action flex-column align-items-start">
    <div class="d-flex w-100 justify-content-between">
      <h4 class="mb-1"><b><a href="{{question.get_absolute_url}}" >{{ question.qus }}</a></b>
      <small>Asked {{ question.updated|timesince }} ago By <b>
      <a href="{{question.user.get_absolute_url}}" >{{ question.user.username }}</a>
      </b></small></h4>
      <small><b>Category:</b> <a href="{{question.category.get_absolute_url}}" >{{ question.category }}</a></small>
    </div>
    <p class="mb-1">{{ question.details|linebreaks|truncatechars:120 }}</p>

  </div>
</div>
{% endfor %}

{% include "questions/paginator.html" %}

{% endblock content %}

templates/questions/search.html
<div style="float: right;">
    <form method='GET' action=''>
        <input type='text' name='q' placeholder='Search' value='{{ request.GET.q }}'/>
        <input class="btn btn-primary" type='submit' value='Search' />
    </form>
</div>
<hr>
{% if request.GET.q %}

<p>showing search results for "{{ request.GET.q }}"</p><br>

{% endif %}