advice_lancing/urls.py
from django.contrib import admin
from django.urls import path, include
from markdownx import urls as markdownx
from django.conf.urls import url
from blog import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('special/', views.special, name = 'special'),
    path('logout/', views.user_logout, name = 'logout'),
    url(r'^questions/', include('questions.urls', namespace='questions')),

]

urlpatterns += [
    url(r'^markdownx/', include(markdownx))
]

blog/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'blog'


urlpatterns = [
    path('', views.allblogs , name='allblogs'),
    path('<int:blog_id>/', views.detail, name="detail"),
    path('about/', views.about, name ="about"),
    path('dark/', views.dark, name ="dark"),
    path('contact/', views.contact, name="contact"),
    path('register/', views.register, name ='register'),
    path('user_login', views.user_login, name ='user_login'),
]

#if not settings.DEBUG: urlpatterns += [ url(r'^uploads/(?P<path>.)$', serve,{'document_root': settings.MEDIA_ROOT})]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

questions/urls.py
from django.conf.urls import url
from .views import (question_list, 
                    question_detail, 
                    question_ask, 
                    question_update, 
                    category_list, 
                    category,
                    answer_update,
                    question_delete,
                    answer_delete,
                    notification)


app_name ='question'


urlpatterns = [
    url(r'^list/$', question_list, name='question_list'),
    url(r'^ask/$', question_ask, name='question_ask'),
    url(r'^notifications/$', notification, name='notification'),
    url(r'^categories/$', category_list, name='category_list'),
    url(r'^categories/(?P<slug>[\w-]+)/$', category, name='category'),
    url(r'^(?P<slug>[\w-]+)/delete/$', question_delete, name='question_delete'),
    url(r'^(?P<slug>[\w-]+)/edit/$', question_update, name='question_update'),
    url(r'^(?P<slug>[\w-]+)/answer/(?P<pk>\d+)/edit/$', answer_update, name='answer_update'),
    url(r'^(?P<slug>[\w-]+)/answer/(?P<pk>\d+)/delete/$', answer_delete, name='answer_delete'),
    url(r'^(?P<slug>[\w-]+)/$', question_detail, name='question_detail'),
]

blog/models.py
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
    def __str__(self):
      return self.user.username



class Blog(models.Model):
    title = models.CharField(max_length=100, null = False, default="")
    subtitle = models.CharField(max_length=200, default="")
    publish_date = models.DateTimeField(default=timezone.now)
    image = models.ImageField(upload_to='images/', default="", null=True)
    photo_caption = models.TextField(default = 'Imaages By owner', null = True)
    body = MarkdownxField()
 
    def summary(self):
        return self.body[:100]
    def pub_date_pretty(self):
        return self.publish_date.strftime('%b %e, %Y')
    
    def formatted_markdown(self):
        return markdownify(self.body)
    
    def __str__(self):
        return self.title


class Comment(models.Model):

    blog = models.ForeignKey(Blog, on_delete = models.CASCADE, related_name = 'comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    creadted = models.DateTimeField(auto_now_add = True)
    active = models.BooleanField(default = True)

    class Meta:
        ordering = ('creadted',)

    def __str__(self):
        return f'Comment by {self.name} on {self.blog}'
        

blog/forms.py
from .models import Comment
from django import forms
from blog.models import UserProfileInfo
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')


class CommentForm(forms.ModelForm):
	class Meta:
		model = Comment
		fields = ('name', 'email','body')

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog,Comment
from django.core.paginator import (Paginator,EmptyPage, PageNotAnInteger)
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import CommentForm
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.utils import timezone
from blog.forms import UserForm


@login_required
def special(request):
    return HttpResponse("You are logged in !")
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('blog:allblogs'))

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        #profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            registered = True
        else:
            print(user_form.errors,profile_form.errors)
    else:
        user_form = UserForm()
    return render(request,'blog/registration.html',
                          {'user_form':user_form,
                           'registered':registered})
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('blog:allblogs'))
            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details given")
    else:
        return render(request, 'blog/login.html', {})

def allblogs(request):
    #blogs = Blog.objects.filter(publish_date__lte=timezone.now()).order_by('-publish_date')
    blogs_list = Blog.objects.all().order_by('-id')
    paginator = Paginator(blogs_list, 2)
    
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try : 
        blogs = paginator.page(page)
    except EmptyPage:
        blogs = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        blogs = paginator.page(paginator.num_pages)

    return render(request, 'blog/allblogs.html', {'blogs':blogs})
 
def detail(request, blog_id):
    blogdetail = get_object_or_404(Blog, pk=blog_id)

    comments = blogdetail.comments.filter(active = True)

    new_comment = None

    if request.method == "POST":
    	comment_form = CommentForm(data=request.POST)
    	if comment_form.is_valid():
    		new_comment = comment_form.save(commit = False)
    		new_comment.blog = blogdetail 
    		new_comment.save()
    else:
    	comment_form = CommentForm()

    return render(request, 'blog/detail.html', {'blog':blogdetail, 'comments':comments, "new_comment":new_comment,'comment_form':comment_form})

def about(request):
	return render(request, 'blog/about.html')

def contact(request):
	return render(request, 'blog/contact.html')

def dark(request):
    return render(request, 'blog/dark.html')

templates/blog/about.html
{% extends "blog/base.html" %}
{% block body_block %}
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('/static/img/about-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>About Me</h1>
                        <hr class="small">
                        <span class="subheading">This is what I do.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum molestiae debitis nobis, quod sapiente qui voluptatum, placeat magni repudiandae accusantium fugit quas labore non rerum possimus, corrupti enim modi! Et.</p>
            </div>
        </div>
    </div>

    {% endblock%}

  

templates/blog/allblogs.html
<!DOCTYPE html>
{% load static %}
<link rel="shortcut icon" href="{%  static 'img/favicon.png' %} ">
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Advise Lancing</title>


    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->

    <!-- Bootstrap Core CSS -->
    <link type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Theme CSS -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style>
img {
  border: 1px solid #ddd; /* Gray border */
  border-radius: 4px;  /* Rounded border */
  padding: 5px; /* Some padding */
  width: 450px; /* Set a small width */
}

/* Add a hover effect (blue shadow) */
img:hover {
  box-shadow: 0 0 2px 1px rgba(0, 140, 186, 0.5);
}

body {
    font-family: arial;
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

</style>


</head>
<body>

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{% url 'blog:allblogs' %}">
                Advise lancing</a>


            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'blog:allblogs' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:about' %}">About</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:allblogs' %}">Blogs</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:contact' %}">Contact Us</a>
                    </li>




          {% if user.is_authenticated %}
          <li>
                <a href="{% url 'questions:question_list' %}">Q n A</a>
            </li>

            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
          <li><a class="navbar-link" href="{% url 'blog:register' %}">Register</a></li>

            <li><a class="navbar-link" href="{% url 'blog:user_login' %}">Login</a></li>
          {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <!-- <header class="intro-header" style="background-image: url('img/home-bg.jpg')"> -->
    <header class="intro-header" style="background-image: url('static/img/home.jpg') ">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Advise Lancing</h1>
                        <hr class="small">
                        <span class="subheading">Here You Write your Subheading</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">

        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                {% if blogs %}
                {% for blog in blogs.object_list %}
                <div class="post-preview">
                    <a href="{% url 'blog:detail' blog.id %}">
                        <h2 class="post-title">
                            {{ blog.title }}
                        </h2>
                        <h4 class="post-subtitle"><u>{{blog.publish_date|date:"d M Y"}}</u></h4>
                        <h3 class="post-subtitle">
                            {{ blog.subtitle}}
                        </h3>

                    </a>
                    <p class="post-meta">{{ blog.publish_date_pretty }}</p>
                </div>
                <br />
                  <img src = "{{ blog.image.url }}" height=280 width=340>
                <br />
                  <p>{{ blog.summary|safe }}</p>
                  <ul class="pager">
                    <li class="next">
                        <a href="{% url 'blog:detail' blog.id %}">Read More &rarr;</a><br>
                    </li>
                </ul>
             {% endfor %}
             {% else %}
             <div>
                 Sorry, There is no post on this blog
             </div>
             {% endif %}
             <div class="pagination">
                <ul class="pager">
                    {% if blogs.has_previous %}
                    <li class="next"><a href="?page = {{ blogs.previous.page_number }}">Previous Page</a></li>
                    {% endif %}
                    {% for bg in blogs.paginator.page_number %}
                        {% if blogs.number == bg %}
                            <li class="active"><a href="?page={{ bg }}">{{bg}}</a></li>
                        {% else%}
                            <li><a href="?page={{ bg }}">{{ bg }}</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if blogs.has_next %}
                    <li class="next"><a href="?page={{ blogs.next_page_number}}">Next Page</a></li>
                    {% endif %}
                </ul>

             </div>

            </div>
        </div>
    </div>


    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Advise lancing 2020</p>
                </div>
            </div>
        </div>
    </footer>


    <!-- jQuery -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Contact Form JavaScript -->
    <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'js/contact_me.js' %}"></script>


    <!-- Theme JavaScript -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>

</body>

</html>

templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<link rel="shortcut icon" href="{%  static 'img/favicon.png' %} ">
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Advise Lancing</title>


    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->

    <!-- Bootstrap Core CSS -->
    <link type="text/css" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Theme CSS -->
    <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

 
</head>
<body> 

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{% url 'blog:allblogs' %}">
                Advise lancing</a>

                
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'blog:allblogs' %}">Home</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:about' %}">About</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:allblogs' %}">Blogs</a>
                    </li>
                    <li>
                        <a href="{% url 'blog:contact' %}">Contact Us</a>
                    </li>
                   

                         
          
          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
            <li>
                <a href="{% url 'questions:question_list' %}">Questions</a>
            </li>
          {% else %}
          <li><a class="navbar-link" href="{% url 'blog:register' %}">Register</a></li>
            <li><a class="navbar-link" href="{% url 'blog:user_login' %}">Login</a></li>
          {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

 

 
    {% block body_block %}
    {% endblock %}


    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Advise lancing 2020</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

    <!-- Contact Form JavaScript -->
    <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'js/contact_me.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>

</body>

</html>

templates/blog/login.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>

Login
</title>
<style type="text/css">
  html {
  height: 100%;
}
body {
  margin:0;
  padding:0;
  font-family: sans-serif;
  background: linear-gradient(#141e30, #243b55);
}

.login-box {
  position: absolute;
  top: 50%;
  left: 50%;
  width: 400px;
  padding: 40px;
  transform: translate(-50%, -50%);
  background: rgba(0,0,0,.5);
  box-sizing: border-box;
  box-shadow: 0 15px 25px rgba(0,0,0,.6);
  border-radius: 10px;
}

.login-box h2 {
  margin: 0 0 30px;
  padding: 0;
  color: #fff;
  text-align: center;
}

.login-box .user-box {
  position: relative;
}

.login-box .user-box input {
  width: 100%;
  padding: 10px 0;
  font-size: 16px;
  color: #fff;
  margin-bottom: 30px;
  border: none;
  border-bottom: 1px solid #fff;
  outline: none;
  background: transparent;
}
.login-box .user-box label {
  position: absolute;
  top:0;
  left: 0;
  padding: 10px 0;
  font-size: 16px;
  color: #fff;
  pointer-events: none;
  transition: .5s;
}

.login-box .user-box input:focus ~ label,
.login-box .user-box input:valid ~ label {
  top: -20px;
  left: 0;
  color: #03e9f4;
  font-size: 12px;
}

.login-box form a {
  position: relative;
  display: inline-block;
  padding: 10px 20px;
  color: #03e9f4;
  font-size: 16px;
  text-decoration: none;
  text-transform: uppercase;
  overflow: hidden;
  transition: .5s;
  margin-top: 40px;
  letter-spacing: 4px
}

.login-box a:hover {
  background: #03e9f4;
  color: #fff;
  border-radius: 5px;
  box-shadow: 0 0 5px #03e9f4,
              0 0 25px #03e9f4,
              0 0 50px #03e9f4,
              0 0 100px #03e9f4;
}

.login-box a span {
  position: absolute;
  display: block;
}

.login-box a span:nth-child(1) {
  top: 0;
  left: -100%;
  width: 100%;
  height: 2px;
  background: linear-gradient(90deg, transparent, #03e9f4);
  animation: btn-anim1 1s linear infinite;
}

@keyframes btn-anim1 {
  0% {
    left: -100%;
  }
  50%,100% {
    left: 100%;
  }
}

.login-box a span:nth-child(2) {
  top: -100%;
  right: 0;
  width: 2px;
  height: 100%;
  background: linear-gradient(180deg, transparent, #03e9f4);
  animation: btn-anim2 1s linear infinite;
  animation-delay: .25s
}

@keyframes btn-anim2 {
  0% {
    top: -100%;
  }
  50%,100% {
    top: 100%;
  }
}

.login-box a span:nth-child(3) {
  bottom: 0;
  right: -100%;
  width: 100%;
  height: 2px;
  background: linear-gradient(270deg, transparent, #03e9f4);
  animation: btn-anim3 1s linear infinite;
  animation-delay: .5s
}

@keyframes btn-anim3 {
  0% {
    right: -100%;
  }
  50%,100% {
    right: 100%;
  }
}

.login-box a span:nth-child(4) {
  bottom: -100%;
  left: 0;
  width: 2px;
  height: 100%;
  background: linear-gradient(360deg, transparent, #03e9f4);
  animation: btn-anim4 1s linear infinite;
  animation-delay: .75s
}

@keyframes btn-anim4 {
  0% {
    bottom: -100%;
  }
  50%,100% {
    bottom: 100%;
  }
}

</style>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> 


  

</head>
<body>
  <div class="login-box">
  <h2>Login</h2>
  <form method="POST" action="{% url 'blog:user_login' %}">
    {% csrf_token %}
    <div class="user-box">
          <input type="text" name="username" placeholder="Username">
    </div>
    <div class="user-box">
      <input type="password" name="password" placeholder="Password">
    </div>
    <a href="#">
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      <button type="submit" class="btn btn-primary">Login</button>
  
    </a>
  </form>
</div>
<!-- 	<div class="container">
    <div class="jumbotron">
      <h1>Login here :</h1>
      &nbsp;
      <form method="post" action="{% url 'blog:user_login' %}">
                  {% csrf_token %}
  <div class="form-group">
    <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username">
          <br><br> &nbsp;
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password">
  </div>
  <div class="form-group form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1">
    <label class="form-check-label" for="exampleCheck1">Remember me</label>
  </div>
  <button type="submit" class="btn btn-primary">Login</button>
  <button type="submit" action="{% url 'blog:register' %}"class="btn btn-primary">Register</button>
</form>
      
 -->

</div>
  </div>

</body>
</html>